[tool.poetry]
name = "source-dbt"
version = "0.1.0"
description = ""
authors = ["Ian Eaves <ian@grai.io>"]
license = "ELv2"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.9.1"
networkx = "^2.8.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
