#on:
#  push:
#    branches:
#      - master
#    paths:
#      - "grai-server/**"
#jobs:
#  upload_image:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Set up Docker Build
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
#
#      - name: Build and Push Docker Image
#        uses: docker/build-push-action@v3
#        with:
#          push: true
#          tags: |
#            ghcr.io/${{ github.repository }}:${{ github.ref }}
#            ghcr.io/${{ github.repository }}:latest